@startuml
actor Utilisateur

usecase "Ecrire un message à un groupe" as UC_Write
usecase "Rejoindre un groupe" as UC_Join  #reuse
usecase "Saisir message" as UC_Saisir
usecase "Envoyer message" as UC_Send

Utilisateur --> UC_Write

UC_Write ..> UC_Join : <<extend>>\n"si pas déjà membre"
UC_Write ..> UC_Saisir : <<include>>
UC_Write ..> UC_Send : <<include>>

@enduml
