@startuml
left to right direction

actor Utilisateur
actor Gestionnaire
actor Administration

usecase "Créer groupe" as UC_Create
usecase "Rejoindre groupe" as UC_Join
usecase "Lister groupes" as UC_List
usecase "Dialoguer sur un groupe" as UC_Chat
usecase "Quitter groupe" as UC_Leave

usecase "Supprimer groupe" as UC_Delete
usecase "Fusionner groupes" as UC_Merge
usecase "Modérer membre" as UC_Moderate

Utilisateur --> UC_Create
Utilisateur --> UC_Join
Utilisateur --> UC_List
Utilisateur --> UC_Chat
Utilisateur --> UC_Leave

Gestionnaire --> UC_Delete
Gestionnaire --> UC_Merge
Gestionnaire --> UC_Moderate

@enduml
