@startuml
actor Gestionnaire

usecase "Modérer un membre" as UC_Mod
usecase "Se loguer" as UC_Log
usecase "Sélectionner groupe" as UC_SelG
usecase "Lister membres" as UC_ListM
usecase "Choisir membre" as UC_ChoixM
usecase "Appliquer sanction" as UC_Sanction

Gestionnaire --> UC_Mod

UC_Mod ..> UC_Log : <<extend>>
UC_Mod ..> UC_SelG : <<include>>
UC_Mod ..> UC_ListM : <<include>>
UC_Mod ..> UC_ChoixM : <<include>>
UC_Mod ..> UC_Sanction : <<extend>>

@enduml
