@startuml
actor Utilisateur

usecase "Lire les messages d'un groupe" as UC_Read
usecase "Rejoindre un groupe" as UC_Join
usecase "Recevoir messages" as UC_Recv
usecase "Afficher messages" as UC_Aff

Utilisateur --> UC_Read

UC_Read ..> UC_Join : <<extend>>\n"si pas déjà membre"
UC_Read ..> UC_Recv : <<include>>
UC_Read ..> UC_Aff : <<include>>

@enduml
