@startuml
actor Utilisateur

usecase "Rejoindre un groupe" as UC_Join
usecase "Se loguer" as UC_Log
usecase "Sélectionner groupe" as UC_Sel
usecase "Vérifier accès" as UC_Verif
usecase "Initialiser session utilisateur" as UC_Sess

Utilisateur --> UC_Join

UC_Join ..> UC_Log : <<extend>>
UC_Join ..> UC_Sel : <<include>>
UC_Join ..> UC_Verif : <<include>>
UC_Join ..> UC_Sess : <<extend>>\n"si accès autorisé"

@enduml
